# Generated by Django 3.2.13 on 2022-07-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sign', '0003_alter_user_favorite_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('favor_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'user_favorite',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='user_infomation',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='User_favorite',
        ),
    ]
