# Generated by Django 3.2.13 on 2022-07-26 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sign', '0004_auto_20220726_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_infomation',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
