# Generated by Django 3.2.13 on 2022-07-26 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sign', '0005_alter_user_infomation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_infomation',
            options={'managed': False},
        ),
    ]
