# Generated by Django 3.2.13 on 2022-07-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sign', '0006_alter_user_infomation_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_infomation',
            table='sign_user_infomation',
        ),
    ]
