# Generated by Django 3.2.13 on 2022-07-26 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sign', '0007_alter_user_infomation_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userfavorite',
            table='sign_user_favorite',
        ),
    ]
