# Generated by Django 3.2.13 on 2022-08-03 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sign', '0009_auto_20220803_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfomation',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'user_infomation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('username', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Sign.userinfomation')),
                ('favor_id', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'user_favorite',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SignUserFavorite',
        ),
        migrations.DeleteModel(
            name='SignUserInfomation',
        ),
    ]
