# Generated by Django 3.2.13 on 2022-08-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sign', '0010_auto_20220803_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_id', models.CharField(max_length=30)),
                ('context', models.TextField(blank=True, null=True)),
                ('image1', models.CharField(blank=True, max_length=255, null=True)),
                ('image2', models.CharField(blank=True, max_length=255, null=True)),
                ('image3', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_review',
                'managed': False,
            },
        ),
    ]
