# Generated by Django 3.2.13 on 2022-08-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sign', '0011_userreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayRecommends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=45)),
                ('category', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'day_recommends',
                'managed': False,
            },
        ),
    ]
