# Generated by Django 3.2.13 on 2022-08-22 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sign', '0012_dayrecommends'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayrecommends',
            options={},
        ),
    ]
