# Generated by Django 3.2.13 on 2022-08-22 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sign', '0013_alter_dayrecommends_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayrecommends',
            options={'managed': False},
        ),
    ]
